spring:
  application:
    name: "cliente-cursos"

server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 20
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
