spring:
  application:
    name: eureka-server

server:
  port: 8671
  waitTimeInMsWhenSyncEmpty: 0

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

