spring:
  application:
    name: "serviciocursos"

server:
  port: 9000
  servlet:
    context-path: /service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
